<!DOCTYPE html>
<html lang="id">

<head>
    <meta charset="UTF-8">
    <title>CoA - {{ $report->no_report }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            color: #333;
        }

        h1,
        h2 {
            text-align: center;
            margin: 0;
            padding: 5px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }

        th,
        td {
            border: 1px solid #555;
            padding: 6px;
            text-align: left;
            font-size: 11px;
        }

        th {
            background-color: #f0f0f0;
        }

        .section {
            margin-top: 20px;
        }

        .info-table td {
            border: none;
            padding: 3px;
        }

        .info-table td.label {
            width: 150px;
            font-weight: bold;
        }

        .footer {
            margin-top: 40px;
            text-align: center;
            font-size: 10px;
            color: #555;
        }
    </style>
</head>

<body>

    <h1>Certificate of Analysis (CoA)</h1>
    <h2>No Report: {{ $report->no_report }}</h2>

    <div class="section">
        <table class="info-table">
            <tr>
                <td class="label">Requested By</td>
                <td>{{ $report->requested_by_name }}</td>
                <td class="label">Department</td>
                <td>{{ $report->department_name }}</td>
            </tr>
            <tr>
                <td class="label">Location</td>
                <td>{{ $report->location }}</td>
                <td class="label">Status</td>
                <td>{{ $report->status_name }}</td>
            </tr>
            <tr>
                <td class="label">Sampling Date</td>
                <td>{{ $report->date_sampling }}</td>
                <td class="label">Analysis Date</td>
                <td>{{ $report->date_analysis }}</td>
            </tr>
            <tr>
                <td class="label">Sampler</td>
                <td>{{ $report->sampler_name }}</td>
                <td class="label">Analyst</td>
                <td>{{ $report->analyst_name }}</td>
            </tr>
            <tr>
                <td class="label">Reviewed By</td>
                <td>{{ $report->reviewed_by_name }}</td>
                <td class="label">Acknowledged By</td>
                <td>{{ $report->acknowledge_by_name }}</td>
            </tr>
        </table>
    </div>

    @if($report->remark)
        <div class="section">
            <strong>Remark:</strong>
            <p>{{ $report->remark }}</p>
        </div>
    @endif

    @if($report->notes)
        <div class="section">
            <strong>Notes:</strong>
            <p>{!! $report->notes !!}</p>
        </div>
    @endif

    <div class="section">
        <table>
            <thead>
                <tr>
                    <th>Bahan Pengujian</th>
                    <th>Test Type</th>
                    <th>Method</th>
                    <th>Standard</th>
                    <th>Result</th>
                    <th>Unit</th>
                    <th>Description</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($testDetails as $td)
                    <tr>
                        <td>{{ $td->bahan_pengujian }}</td>
                        <td>{{ $td->test_type }}</td>
                        <td>{{ $td->method }}</td>
                        <td>{{ $td->standard }}</td>
                        <td>{{ $td->result }}</td>
                        <td>{{ $td->unit }}</td>
                        <td>{{ $td->description ?? '-' }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>

    <div class="footer">
        Generated by Laboratory Management System - {{ date('d/m/Y H:i') }}
    </div>

</body>

</html>